-- +goose Up
CREATE TABLE SCHOOLS (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    postal_code VARCHAR(255),
    prefecture VARCHAR(255),
    city VARCHAR(255),
    address VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE TEACHERS (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255),
    firebase_uid VARCHAR(255),
    school_id BIGINT,
    FOREIGN KEY (school_id) REFERENCES SCHOOLS(id),
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE CLASSES (
    id BIGSERIAL PRIMARY KEY,
    uuid CHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    teacher_id BIGINT,
    UNIQUE (uuid),
    FOREIGN KEY (teacher_id) REFERENCES TEACHERS(id),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE STUDENTS (
    id BIGSERIAL PRIMARY KEY,
    student_no INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    sex INTEGER NOT NULL,
    memo TEXT,
    class_id BIGINT,
    FOREIGN KEY (class_id) REFERENCES CLASSES(id),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE SURVEYS (
    id BIGSERIAL PRIMARY KEY,
    uuid CHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    status INTEGER NOT NULL DEFAULT 0,
    class_id BIGINT,
    UNIQUE (uuid),
    FOREIGN KEY (class_id) REFERENCES CLASSES(id),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE TEAMS (
    id BIGSERIAL PRIMARY KEY,
    team_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    survey_id BIGINT,
    FOREIGN KEY (survey_id) REFERENCES SURVEYS(id),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (survey_id, team_id)
);

CREATE TABLE STUDENT_PREFERENCES (
    id BIGSERIAL PRIMARY KEY,
    student_id BIGINT,
    survey_id BIGINT,
    team_id BIGINT,
    mi_a INTEGER NOT NULL,
    mi_b INTEGER NOT NULL,
    mi_c INTEGER NOT NULL,
    mi_d INTEGER NOT NULL,
    mi_e INTEGER NOT NULL,
    mi_f INTEGER NOT NULL,
    mi_g INTEGER NOT NULL,
    mi_h INTEGER NOT NULL,
    leader INTEGER NOT NULL,
    eyesight INTEGER NOT NULL,
    FOREIGN KEY (student_id) REFERENCES STUDENTS(id),
    FOREIGN KEY (survey_id) REFERENCES SURVEYS(id),
    FOREIGN KEY (team_id) REFERENCES TEAMS(id),
    UNIQUE (student_id, survey_id),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE STUDENT_DISLIKES (
    id BIGSERIAL PRIMARY KEY,
    student_id BIGINT,
    preference_id BIGINT,
    FOREIGN KEY (student_id) REFERENCES STUDENTS(id),
    FOREIGN KEY (preference_id) REFERENCES STUDENT_PREFERENCES(id),
    UNIQUE (student_id, preference_id),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);


-- +goose Down
DROP TABLE IF EXISTS STUDENT_DISLIKES;
DROP TABLE IF EXISTS STUDENT_PREFERENCES;
DROP TABLE IF EXISTS TEAMS;
DROP TABLE IF EXISTS SURVEYS;
DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS CLASSES;
DROP TABLE IF EXISTS TEACHERS;
DROP TABLE IF EXISTS SCHOOLS;
