##### 2023/03
POST http://localhost:8000/solve HTTP/1.1
content-type: application/json

{
    "class_id": 1,
    "max_team_num": 3,
    "timeout": 120,
    "flavors": [
        {
            "mi_a": 1,
            "mi_b": 1,
            "mi_c": 3,
            "mi_d": 1,
            "mi_e": 3,
            "mi_f": 5,
            "mi_g": 1,
            "mi_h": 2,
            "leader": 1,
            "eyesight": 3,
            "sex": 0,
            "dislikes": [
                
            ],
            "previous": 0
        },
        {
            "mi_a": 9,
            "mi_b": 9,
            "mi_c": 8,
            "mi_d": 6,
            "mi_e": 8,
            "mi_f": 8,
            "mi_g": 8,
            "mi_h": 8,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                22
            ],
            "previous": 1
        },
        {
            "mi_a": 2,
            "mi_b": 3,
            "mi_c": 9,
            "mi_d": 8,
            "mi_e": 6,
            "mi_f": 8,
            "mi_g": 7,
            "mi_h": 8,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                1
            ],
            "previous": 2
        },
        {
            "mi_a": 6,
            "mi_b": 6,
            "mi_c": 7,
            "mi_d": 6,
            "mi_e": 6,
            "mi_f": 7,
            "mi_g": 6,
            "mi_h": 5,
            "leader": 1,
            "eyesight": 8,
            "sex": 0,
            "dislikes": [
                1,7
            ],
            "previous": 3
        },
        {
            "mi_a": 5,
            "mi_b": 5,
            "mi_c": 4,
            "mi_d": 3,
            "mi_e": 4,
            "mi_f": 5,
            "mi_g": 5,
            "mi_h": 3,
            "leader": 1,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 1
        },
        {
            "mi_a": 6,
            "mi_b": 4,
            "mi_c": 5,
            "mi_d": 2,
            "mi_e": 3,
            "mi_f": 2,
            "mi_g": 3,
            "mi_h": 7,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                6, 7
            ],
            "previous": 4
        },
        {
            "mi_a": 2,
            "mi_b": 5,
            "mi_c": 6,
            "mi_d": 5,
            "mi_e": 3,
            "mi_f": 6,
            "mi_g": 8,
            "mi_h": 3,
            "leader": 3,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                16, 5, 7
            ],
            "previous": 5
        },
        {
            "mi_a": 6,
            "mi_b": 8,
            "mi_c": 6,
            "mi_d": 5,
            "mi_e": 8,
            "mi_f": 4,
            "mi_g": 7,
            "mi_h": 8,
            "leader": 1,
            "eyesight": 8,
            "sex": 0,
            "dislikes": [
                16,22, 5, 6
            ],
            "previous": 0
        },
        {
            "mi_a": 4,
            "mi_b": 4,
            "mi_c": 3,
            "mi_d": 2,
            "mi_e": 4,
            "mi_f": 4,
            "mi_g": 3,
            "mi_h": 3,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                
            ],
            "previous": 6
        },
        {
            "mi_a": 2,
            "mi_b": 5,
            "mi_c": 2,
            "mi_d": 1,
            "mi_e": 2,
            "mi_f": 4,
            "mi_g": 5,
            "mi_h": 5,
            "leader": 8,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 1
        },
        {
            "mi_a": 4,
            "mi_b": 8,
            "mi_c": 5,
            "mi_d": 5,
            "mi_e": 8,
            "mi_f": 6,
            "mi_g": 4,
            "mi_h": 7,
            "leader": 8,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 5
        },
        {
            "mi_a": 5,
            "mi_b": 2,
            "mi_c": 1,
            "mi_d": 1,
            "mi_e": 4,
            "mi_f": 3,
            "mi_g": 7,
            "mi_h": 6,
            "leader": 1,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                4,20,6,14,17
            ],
            "previous": 2
        },
        {
            "mi_a": 5,
            "mi_b": 8,
            "mi_c": 8,
            "mi_d": 6,
            "mi_e": 6,
            "mi_f": 5,
            "mi_g": 9,
            "mi_h": 9,
            "leader": 3,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 0
        },
        {
            "mi_a": 4,
            "mi_b": 5,
            "mi_c": 4,
            "mi_d": 2,
            "mi_e": 6,
            "mi_f": 5,
            "mi_g": 2,
            "mi_h": 4,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                
            ],
            "previous": 7
        },
        {
            "mi_a": 3,
            "mi_b": 4,
            "mi_c": 5,
            "mi_d": 4,
            "mi_e": 6,
            "mi_f": 4,
            "mi_g": 7,
            "mi_h": 4,
            "leader": 8,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 4
        },
        {
            "mi_a": 7,
            "mi_b": 6,
            "mi_c": 5,
            "mi_d": 1,
            "mi_e": 4,
            "mi_f": 8,
            "mi_g": 9,
            "mi_h": 7,
            "leader": 1,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 8
        },
        {
            "mi_a": 4,
            "mi_b": 5,
            "mi_c": 6,
            "mi_d": 1,
            "mi_e": 4,
            "mi_f": 3,
            "mi_g": 4,
            "mi_h": 9,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                
            ],
            "previous": 5
        },
        {
            "mi_a": 1,
            "mi_b": 3,
            "mi_c": 5,
            "mi_d": 1,
            "mi_e": 3,
            "mi_f": 6,
            "mi_g": 7,
            "mi_h": 5,
            "leader": 1,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 6
        },
        {
            "mi_a": 4,
            "mi_b": 7,
            "mi_c": 5,
            "mi_d": 5,
            "mi_e": 7,
            "mi_f": 6,
            "mi_g": 8,
            "mi_h": 7,
            "leader": 8,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                5,21
            ],
            "previous": 7
        },
        {
            "mi_a": 4,
            "mi_b": 5,
            "mi_c": 4,
            "mi_d": 3,
            "mi_e": 5,
            "mi_f": 4,
            "mi_g": 3,
            "mi_h": 7,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                
            ],
            "previous": 3
        },
        {
            "mi_a": 5,
            "mi_b": 6,
            "mi_c": 5,
            "mi_d": 3,
            "mi_e": 2,
            "mi_f": 2,
            "mi_g": 8,
            "mi_h": 5,
            "leader": 1,
            "eyesight": 3,
            "sex": 1,
            "dislikes": [
                21
            ],
            "previous": 3
        },
        {
            "mi_a": 6,
            "mi_b": 7,
            "mi_c": 6,
            "mi_d": 4,
            "mi_e": 6,
            "mi_f": 4,
            "mi_g": 6,
            "mi_h": 6,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                
            ],
            "previous": 2
        },
        {
            "mi_a": 5,
            "mi_b": 7,
            "mi_c": 5,
            "mi_d": 4,
            "mi_e": 3,
            "mi_f": 5,
            "mi_g": 8,
            "mi_h": 9,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                
            ],
            "previous": 8
        },
        {
            "mi_a": 4,
            "mi_b": 7,
            "mi_c": 7,
            "mi_d": 6,
            "mi_e": 8,
            "mi_f": 7,
            "mi_g": 8,
            "mi_h": 9,
            "leader": 3,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 8
        },
        {
            "mi_a": 6,
            "mi_b": 7,
            "mi_c": 9,
            "mi_d": 9,
            "mi_e": 9,
            "mi_f": 8,
            "mi_g": 3,
            "mi_h": 9,
            "leader": 8,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                1
            ],
            "previous": 6
        },
        {
            "mi_a": 7,
            "mi_b": 8,
            "mi_c": 6,
            "mi_d": 4,
            "mi_e": 5,
            "mi_f": 5,
            "mi_g": 9,
            "mi_h": 7,
            "leader": 1,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 4
        },
        {
            "mi_a": 2,
            "mi_b": 3,
            "mi_c": 2,
            "mi_d": 2,
            "mi_e": 3,
            "mi_f": 2,
            "mi_g": 4,
            "mi_h": 3,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                
            ],
            "previous": 7
        }
    ]
}

##### 2023/03 with dummy
POST http://localhost:8000/solve HTTP/1.1
content-type: application/json

{
    "class_id": 1,
    "max_team_num": 3,
    "timeout": 120,
    "flavors": [
        {
            "mi_a": 1,
            "mi_b": 1,
            "mi_c": 3,
            "mi_d": 1,
            "mi_e": 3,
            "mi_f": 5,
            "mi_g": 1,
            "mi_h": 2,
            "leader": 1,
            "eyesight": 3,
            "sex": 0,
            "dislikes": [
                
            ],
            "previous": 0
        },
        {
            "mi_a": 9,
            "mi_b": 9,
            "mi_c": 8,
            "mi_d": 6,
            "mi_e": 8,
            "mi_f": 8,
            "mi_g": 8,
            "mi_h": 8,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                22
            ],
            "previous": 1
        },
        {
            "mi_a": 2,
            "mi_b": 3,
            "mi_c": 9,
            "mi_d": 8,
            "mi_e": 6,
            "mi_f": 8,
            "mi_g": 7,
            "mi_h": 8,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                1
            ],
            "previous": 2
        },
        {
            "mi_a": 6,
            "mi_b": 6,
            "mi_c": 7,
            "mi_d": 6,
            "mi_e": 6,
            "mi_f": 7,
            "mi_g": 6,
            "mi_h": 5,
            "leader": 1,
            "eyesight": 8,
            "sex": 0,
            "dislikes": [
                1,7
            ],
            "previous": 3
        },
        {
            "mi_a": 5,
            "mi_b": 5,
            "mi_c": 4,
            "mi_d": 3,
            "mi_e": 4,
            "mi_f": 5,
            "mi_g": 5,
            "mi_h": 3,
            "leader": 1,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 1
        },
        {
            "mi_a": 6,
            "mi_b": 4,
            "mi_c": 5,
            "mi_d": 2,
            "mi_e": 3,
            "mi_f": 2,
            "mi_g": 3,
            "mi_h": 7,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                6,7
            ],
            "previous": 4
        },
        {
            "mi_a": 2,
            "mi_b": 5,
            "mi_c": 6,
            "mi_d": 5,
            "mi_e": 3,
            "mi_f": 6,
            "mi_g": 8,
            "mi_h": 3,
            "leader": 3,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                16, 5, 7
            ],
            "previous": 5
        },
        {
            "mi_a": 6,
            "mi_b": 8,
            "mi_c": 6,
            "mi_d": 5,
            "mi_e": 8,
            "mi_f": 4,
            "mi_g": 7,
            "mi_h": 8,
            "leader": 1,
            "eyesight": 8,
            "sex": 0,
            "dislikes": [
                16,22, 5, 6
            ],
            "previous": 0
        },
        {
            "mi_a": 4,
            "mi_b": 4,
            "mi_c": 3,
            "mi_d": 2,
            "mi_e": 4,
            "mi_f": 4,
            "mi_g": 3,
            "mi_h": 3,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                
            ],
            "previous": 6
        },
        {
            "mi_a": 2,
            "mi_b": 5,
            "mi_c": 2,
            "mi_d": 1,
            "mi_e": 2,
            "mi_f": 4,
            "mi_g": 5,
            "mi_h": 5,
            "leader": 8,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 1
        },
        {
            "mi_a": 4,
            "mi_b": 8,
            "mi_c": 5,
            "mi_d": 5,
            "mi_e": 8,
            "mi_f": 6,
            "mi_g": 4,
            "mi_h": 7,
            "leader": 8,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 5
        },
        {
            "mi_a": 5,
            "mi_b": 2,
            "mi_c": 1,
            "mi_d": 1,
            "mi_e": 4,
            "mi_f": 3,
            "mi_g": 7,
            "mi_h": 6,
            "leader": 1,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                4,20,6,14,17
            ],
            "previous": 2
        },
        {
            "mi_a": 5,
            "mi_b": 8,
            "mi_c": 8,
            "mi_d": 6,
            "mi_e": 6,
            "mi_f": 5,
            "mi_g": 9,
            "mi_h": 9,
            "leader": 3,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 0
        },
        {
            "mi_a": 4,
            "mi_b": 5,
            "mi_c": 4,
            "mi_d": 2,
            "mi_e": 6,
            "mi_f": 5,
            "mi_g": 2,
            "mi_h": 4,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                
            ],
            "previous": 7
        },
        {
            "mi_a": 3,
            "mi_b": 4,
            "mi_c": 5,
            "mi_d": 4,
            "mi_e": 6,
            "mi_f": 4,
            "mi_g": 7,
            "mi_h": 4,
            "leader": 8,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 4
        },
        {
            "mi_a": 7,
            "mi_b": 6,
            "mi_c": 5,
            "mi_d": 1,
            "mi_e": 4,
            "mi_f": 8,
            "mi_g": 9,
            "mi_h": 7,
            "leader": 1,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 8
        },
        {
            "mi_a": 4,
            "mi_b": 5,
            "mi_c": 6,
            "mi_d": 1,
            "mi_e": 4,
            "mi_f": 3,
            "mi_g": 4,
            "mi_h": 9,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                
            ],
            "previous": 5
        },
        {
            "mi_a": 1,
            "mi_b": 3,
            "mi_c": 5,
            "mi_d": 1,
            "mi_e": 3,
            "mi_f": 6,
            "mi_g": 7,
            "mi_h": 5,
            "leader": 1,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 6
        },
        {
            "mi_a": 4,
            "mi_b": 7,
            "mi_c": 5,
            "mi_d": 5,
            "mi_e": 7,
            "mi_f": 6,
            "mi_g": 8,
            "mi_h": 7,
            "leader": 8,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                5,21
            ],
            "previous": 7
        },
        {
            "mi_a": 4,
            "mi_b": 5,
            "mi_c": 4,
            "mi_d": 3,
            "mi_e": 5,
            "mi_f": 4,
            "mi_g": 3,
            "mi_h": 7,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                
            ],
            "previous": 3
        },
        {
            "mi_a": 5,
            "mi_b": 6,
            "mi_c": 5,
            "mi_d": 3,
            "mi_e": 2,
            "mi_f": 2,
            "mi_g": 8,
            "mi_h": 5,
            "leader": 1,
            "eyesight": 3,
            "sex": 1,
            "dislikes": [
                21
            ],
            "previous": 3
        },
        {
            "mi_a": 6,
            "mi_b": 7,
            "mi_c": 6,
            "mi_d": 4,
            "mi_e": 6,
            "mi_f": 4,
            "mi_g": 6,
            "mi_h": 6,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                
            ],
            "previous": 2
        },
        {
            "mi_a": 5,
            "mi_b": 7,
            "mi_c": 5,
            "mi_d": 4,
            "mi_e": 3,
            "mi_f": 5,
            "mi_g": 8,
            "mi_h": 9,
            "leader": 1,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                
            ],
            "previous": 8
        },
        {
            "mi_a": 4,
            "mi_b": 7,
            "mi_c": 7,
            "mi_d": 6,
            "mi_e": 8,
            "mi_f": 7,
            "mi_g": 8,
            "mi_h": 9,
            "leader": 3,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 8
        },
        {
            "mi_a": 6,
            "mi_b": 7,
            "mi_c": 9,
            "mi_d": 9,
            "mi_e": 9,
            "mi_f": 8,
            "mi_g": 3,
            "mi_h": 9,
            "leader": 8,
            "eyesight": 1,
            "sex": 0,
            "dislikes": [
                1
            ],
            "previous": 6
        },
        {
            "mi_a": 7,
            "mi_b": 8,
            "mi_c": 6,
            "mi_d": 4,
            "mi_e": 5,
            "mi_f": 5,
            "mi_g": 9,
            "mi_h": 7,
            "leader": 1,
            "eyesight": 1,
            "sex": 1,
            "dislikes": [
                
            ],
            "previous": 4
        }
    ]
}
